# Generated by Django 5.0.6 on 2024-07-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipodefutbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('siglas', models.CharField(max_length=30)),
                ('seguidores', models.IntegerField()),
                ('campeonatos', models.IntegerField()),
                ('estadio', models.CharField(max_length=100)),
            ],
        ),
    ]
